# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolymarketCli < Formula
  desc "Polymarket companion CLI (pmctl)"
  homepage "https://github.com/0xfakeSpike/polymarket-go"
  version "1.0.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.19/polymarket-go_1.0.19_darwin_x86_64.tar.gz"
      sha256 "cf9dfe6216d46ba39087e1327dce1939e465bb77ca1cfbb8e36647521802f7bb"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.19/polymarket-go_1.0.19_darwin_arm64.tar.gz"
      sha256 "f00453e476b4d7604f4c49e7f45366862539bb5e12ed75a06aeab4b7bd9ad890"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.19/polymarket-go_1.0.19_linux_x86_64.tar.gz"
      sha256 "3046af91bb9b54977ab1d0fc6218fb4eda9d526827b4f776d359b372929ec984"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.19/polymarket-go_1.0.19_linux_arm64.tar.gz"
      sha256 "5bfaca3906b83dcfdf27dc9af5cad7710129edf0fa551de9237f33f1e6445dd3"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  test do
    assert_match "pmctl - Polymarket CLI", shell_output("#{bin}/pmctl 2>&1", 2)
  end
end
