# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolymarketCli < Formula
  desc "Polymarket companion CLI (pmctl)"
  homepage "https://github.com/0xfakeSpike/polymarket-go"
  version "1.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.18/polymarket-go_1.0.18_darwin_x86_64.tar.gz"
      sha256 "de2e73f495dfc5fc6f33396cfd3dd492cdbd0dd156087c047bbfef2966c29299"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.18/polymarket-go_1.0.18_darwin_arm64.tar.gz"
      sha256 "993b2c8a535a8431aa00247a1c457ab518b2ec64862897fa45db2c7f8f6b9c14"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.18/polymarket-go_1.0.18_linux_x86_64.tar.gz"
      sha256 "200e8b7b84571fe583eefb15a0d9a649656a74862370c15c9883b3470c639135"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.18/polymarket-go_1.0.18_linux_arm64.tar.gz"
      sha256 "480ab3040c81d619d80677d49a040a5f052af62d9eb2c5a2fd185a81e514b5e3"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  test do
    assert_match "pmctl - Polymarket CLI", shell_output("#{bin}/pmctl 2>&1", 2)
  end
end
