# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolymarketGo < Formula
  desc "Polymarket Go companion CLI"
  homepage "https://github.com/0xfakeSpike/polymarket-go"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.10/polymarket-go_1.0.10_darwin_x86_64.tar.gz"
      sha256 "96850b421ae2f9f9f6c95c3bc31234f7071d59c64b81b48f3d9ac87b04532ba4"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.10/polymarket-go_1.0.10_darwin_arm64.tar.gz"
      sha256 "ebb0b8162f571cf5202ee9afc7b4f35ca9d5415ac76cbe8ba6e0c5146999f574"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.10/polymarket-go_1.0.10_linux_x86_64.tar.gz"
      sha256 "6075f99f85c1f45d2ffda2666c5212ac9960b9c93e6d5be2ecbb3199a52d630f"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.10/polymarket-go_1.0.10_linux_arm64.tar.gz"
      sha256 "fc62efff8614d3cc1f3b1280d9e6dd37dd42b28a23a8a0d656e54145ecf913bd"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  test do
    assert_match "pmctl - Polymarket CLI", shell_output("#{bin}/pmctl 2>&1", 2)
  end
end
