# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolymarketGo < Formula
  desc "Polymarket Go companion CLI"
  homepage "https://github.com/0xfakeSpike/polymarket-go"
  version "1.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.11/polymarket-go_1.0.11_darwin_x86_64.tar.gz"
      sha256 "8f8bf7ec686cdcbd87758c08adde2de29d2b506df73645c8f7e37cee3a43fcaf"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.11/polymarket-go_1.0.11_darwin_arm64.tar.gz"
      sha256 "d4bd69d682ae7a618770794590d7604221835c35c52105721a4991296c02872e"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.11/polymarket-go_1.0.11_linux_x86_64.tar.gz"
      sha256 "50b3932a64f07e1c5a7c5d5f600e1281eda32ffe0b7f105e3ec1ece4c33f86fb"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.11/polymarket-go_1.0.11_linux_arm64.tar.gz"
      sha256 "8244772d0af861d6ea572299117f6e5f835fc7226273a99b8743f211adc11c11"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  test do
    assert_match "pmctl - Polymarket CLI", shell_output("#{bin}/pmctl 2>&1", 2)
  end
end
