# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolymarketGo < Formula
  desc "Polymarket Go companion CLI"
  homepage "https://github.com/0xfakeSpike/polymarket-go"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.7/polymarket-go_1.0.7_darwin_x86_64.tar.gz"
      sha256 "24464ab8c258b4d5353095e99812cbe7a6ecc038b74f0ec7f060eeeb1d0aeebb"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.7/polymarket-go_1.0.7_darwin_arm64.tar.gz"
      sha256 "d8498e176bbe82b0978bd4704ce1992b3d521df6b640fadc181f2682747673d6"

      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.7/polymarket-go_1.0.7_linux_x86_64.tar.gz"
      sha256 "c21e8823c557f968958a22fe0961503ceaccab99e3bbf7e588dfbcca1758d620"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.7/polymarket-go_1.0.7_linux_arm64.tar.gz"
      sha256 "52868358fb3bf998bfda668ec248e70759ab2ba881850d02b48eb01105dfc80b"
      define_method(:install) do
        bin.install "pmctl"
      end
    end
  end

  test do
    assert_match "pmctl - Polymarket CLI", shell_output("#{bin}/pmctl 2>&1", 2)
  end
end
