# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolymarketMcp < Formula
  desc "Polymarket MCP stdio bridge"
  homepage "https://github.com/0xfakeSpike/polymarket-go"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.8/polymarket-go-mcp_1.0.8_darwin_x86_64.tar.gz"
      sha256 "660673ac75ebe1957c23279636f46cef88dd01e1ce30f4ff6afecd3bd1368697"

      define_method(:install) do
        bin.install "polymarket-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.8/polymarket-go-mcp_1.0.8_darwin_arm64.tar.gz"
      sha256 "2f9b9ba247b8f3668282aa9927be0fed653c0827b1e418b59e009f95275b7984"

      define_method(:install) do
        bin.install "polymarket-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.8/polymarket-go-mcp_1.0.8_linux_x86_64.tar.gz"
      sha256 "cc7cf77f9f3eeb7931955c0652fe7a9c8f5344df78810313da17901d8847337a"
      define_method(:install) do
        bin.install "polymarket-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfakeSpike/polymarket-go/releases/download/v1.0.8/polymarket-go-mcp_1.0.8_linux_arm64.tar.gz"
      sha256 "bf23f0c9496d46373afe010bf6dd6db6a7e396bfbe7e64ea606367b7418d888d"
      define_method(:install) do
        bin.install "polymarket-mcp"
      end
    end
  end

  test do
    shell_output("#{bin}/polymarket-mcp </dev/null")
  end
end
